package com.whisperlivekit.translate.model

data class Language(
    val code: String,
    val displayName: String,
    val isAutoDetect: Boolean = false,
)

object LanguageCatalog {
    val languages: List<Language> = listOf(
        Language("auto", "Detect language", isAutoDetect = true),
        Language("af", "Afrikaans"),
        Language("ak", "Akan"),
        Language("am", "Amharic"),
        Language("ar", "Arabic"),
        Language("as", "Assamese"),
        Language("ay", "Aymara"),
        Language("az", "Azerbaijani"),
        Language("ba", "Bashkir"),
        Language("be", "Belarusian"),
        Language("bg", "Bulgarian"),
        Language("bho", "Bhojpuri"),
        Language("bn", "Bengali"),
        Language("bs", "Bosnian"),
        Language("ca", "Catalan"),
        Language("ceb", "Cebuano"),
        Language("ckb", "Kurdish (Sorani)"),
        Language("co", "Corsican"),
        Language("cs", "Czech"),
        Language("cy", "Welsh"),
        Language("da", "Danish"),
        Language("de", "German"),
        Language("dv", "Dhivehi"),
        Language("dz", "Dzongkha"),
        Language("ee", "Ewe"),
        Language("el", "Greek"),
        Language("en", "English"),
        Language("eo", "Esperanto"),
        Language("es", "Spanish"),
        Language("et", "Estonian"),
        Language("eu", "Basque"),
        Language("fa", "Persian"),
        Language("fi", "Finnish"),
        Language("fil", "Filipino"),
        Language("fj", "Fijian"),
        Language("fo", "Faroese"),
        Language("fr", "French"),
        Language("fy", "Frisian"),
        Language("ga", "Irish"),
        Language("gd", "Scottish Gaelic"),
        Language("gl", "Galician"),
        Language("gn", "Guarani"),
        Language("gu", "Gujarati"),
        Language("ha", "Hausa"),
        Language("haw", "Hawaiian"),
        Language("he", "Hebrew"),
        Language("hi", "Hindi"),
        Language("hmn", "Hmong"),
        Language("hr", "Croatian"),
        Language("ht", "Haitian Creole"),
        Language("hu", "Hungarian"),
        Language("hy", "Armenian"),
        Language("ia", "Interlingua"),
        Language("id", "Indonesian"),
        Language("ig", "Igbo"),
        Language("is", "Icelandic"),
        Language("it", "Italian"),
        Language("ja", "Japanese"),
        Language("jv", "Javanese"),
        Language("ka", "Georgian"),
        Language("kk", "Kazakh"),
        Language("km", "Khmer"),
        Language("kn", "Kannada"),
        Language("ko", "Korean"),
        Language("kri", "Krio"),
        Language("ku", "Kurdish (Kurmanji)"),
        Language("ky", "Kyrgyz"),
        Language("la", "Latin"),
        Language("lb", "Luxembourgish"),
        Language("lg", "Luganda"),
        Language("ln", "Lingala"),
        Language("lo", "Lao"),
        Language("lt", "Lithuanian"),
        Language("lv", "Latvian"),
        Language("mg", "Malagasy"),
        Language("mi", "Maori"),
        Language("mk", "Macedonian"),
        Language("ml", "Malayalam"),
        Language("mn", "Mongolian"),
        Language("mr", "Marathi"),
        Language("ms", "Malay"),
        Language("mt", "Maltese"),
        Language("my", "Myanmar"),
        Language("ne", "Nepali"),
        Language("nl", "Dutch"),
        Language("no", "Norwegian"),
        Language("nso", "Northern Sotho"),
        Language("ny", "Chichewa"),
        Language("om", "Oromo"),
        Language("or", "Odia"),
        Language("pa", "Punjabi"),
        Language("pl", "Polish"),
        Language("ps", "Pashto"),
        Language("pt", "Portuguese"),
        Language("qu", "Quechua"),
        Language("ro", "Romanian"),
        Language("ru", "Russian"),
        Language("rw", "Kinyarwanda"),
        Language("sa", "Sanskrit"),
        Language("sd", "Sindhi"),
        Language("si", "Sinhala"),
        Language("sk", "Slovak"),
        Language("sl", "Slovenian"),
        Language("sm", "Samoan"),
        Language("sn", "Shona"),
        Language("so", "Somali"),
        Language("sq", "Albanian"),
        Language("sr", "Serbian"),
        Language("st", "Sesotho"),
        Language("su", "Sundanese"),
        Language("sv", "Swedish"),
        Language("sw", "Swahili"),
        Language("ta", "Tamil"),
        Language("te", "Telugu"),
        Language("tg", "Tajik"),
        Language("th", "Thai"),
        Language("ti", "Tigrinya"),
        Language("tk", "Turkmen"),
        Language("tl", "Tagalog"),
        Language("tn", "Tswana"),
        Language("tr", "Turkish"),
        Language("ts", "Tsonga"),
        Language("tt", "Tatar"),
        Language("ug", "Uyghur"),
        Language("uk", "Ukrainian"),
        Language("ur", "Urdu"),
        Language("uz", "Uzbek"),
        Language("vi", "Vietnamese"),
        Language("wo", "Wolof"),
        Language("xh", "Xhosa"),
        Language("yi", "Yiddish"),
        Language("yo", "Yoruba"),
        Language("zh", "Chinese (Mandarin)"),
        Language("zh-CN", "Chinese Simplified"),
        Language("zh-TW", "Chinese Traditional"),
        Language("zu", "Zulu"),
    )

    val defaultSource: Language = languages.first()
    val defaultTarget: Language = languages.first { it.code == "en" }
}
